<?xml version='1.0' standalone='yes'?>
<config>
<version>0.6.9</version>
<admin_name>admin</admin_name>
<admin_pass>00b3d8304d4e0adf7459220b021c95f9</admin_pass>
<!--<admin_pass>d41d8cd98f00b204e9800998ecf8427e</admin_pass>-->
<host>127.0.0.1</host>
<port>6600</port>
<pass></pass>
<output>0</output>
<template>techno-light</template>
<language>fr</language>
<volume>100</volume>
<repeat></repeat>
<random></random>
<fade>5</fade>
<rights>
<add_songs>selected</add_songs>
<start_playing>selected</start_playing>
<pause_playing>selected</pause_playing>
<set_volume>selected</set_volume>
<controll_playlist>selected</controll_playlist>
<controll_player>selected</controll_player>
<admin_relaxx>selected</admin_relaxx>
<admin_mpd>selected</admin_mpd>
</rights>
<plcolumns>Pos:Artist:Title:Album:Genre:Time</plcolumns>
<trcolumns>Artist:Title:Genre:Time</trcolumns>
</config>
